#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
yarn run check-format ||
(
    echo 'Prettier Check Failed. Run yarn run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
yarn run check-lint ||
(
        echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

# Check tsconfig standards
yarn run check-types ||
(
    echo 'Failed Type check.'
    false;
)

# If everything passes... Now we can commit
echo 'Code looks good to me... Trying to build now.'

yarn run build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why.
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ I am committing this now. ✅✅✅✅'
